Settings Screen
dashxhq/dashx-demo-android pull request #6
Opened 2022-07-26 13:28 UTC by sravank9

- Implemented Settings screen

https://user-images.githubusercontent.com/108011305/181016188-699f5c5c-968c-4e8c-9dc5-787783a925b1.mp4

2022-07-28 03:56 UTC, RabidFire commented on app/src/main/java/com/dashxdemo/app/application/MyApplication.kt
> +        DashXClient.createInstance(this,"TLy2w3kxf8ePXEyEjTepcPiq","https://api.dashx-staging.com/graphql","staging")
Keys shouldn't be hard-coded. We should provide best practices -- how the user would configure this (per environment) in their application.

2022-07-28 04:35 UTC, RabidFire commented on app/src/main/java/com/dashxdemo/app/api/responses/SavedPreferencesResponse.kt
> +data class SavedPreferencesResponse(
Remove this class

2022-07-28 04:39 UTC, RabidFire commented on app/src/main/java/com/dashxdemo/app/api/responses/StoredPreferenceResponse.kt
> +data class StoredPreferenceResponse(
Rename to StoredPreferencesResponse

2022-08-01 12:25 UTC, RabidFire requested changes

2022-08-01 12:25 UTC, RabidFire commented on app/build.gradle
> +    //DashX
Add space after `//`

2022-08-01 12:25 UTC, RabidFire commented on app/src/main/java/com/dashxdemo/app/api/responses/StoredPreferenceResponse.kt
> +data class StoredPreferenceData(
We need to use the SDK class now

2022-08-01 12:25 UTC, RabidFire commented on app/src/main/java/com/dashxdemo/app/application/MyApplication.kt
> +        DashXClient.createInstance(this,"TLy2w3kxf8ePXEyEjTepcPiq","https://api.dashx-staging.com/graphql","staging")
These should not be hard-coded.

2022-08-01 12:25 UTC, RabidFire commented on app/src/main/res/navigation/navigation_login.xml
> +
Remove extra space

2022-08-01 12:25 UTC, RabidFire commented on app/src/main/res/values/strings.xml
> +    <string name="bookmarksPostNotification">"This will send a notification when someone bookmarks a post   "</string>
Why are there quotes and extra spaces here in this string?

2022-08-01 12:25 UTC, RabidFire commented on app/src/main/res/values/strings.xml
> +    <string name="bookmarksPostNotification">"This will send a notification when someone bookmarks a post   "</string>
The string names for the preferences can be based on the preference identifiers themselves:

```
- newPostNotification
- newPostNotificationHint
- newBookmarkNotification
- newBookmarkNotificationHint
```

2022-08-02 05:36 UTC, sravank9 commented
@RabidFire  We need to push our SDK changes, to get this code run
We can get back here once the SDK changes were pushed to maven

2022-08-05 06:26 UTC, RabidFire commented on app/build.gradle
> +        buildConfigField 'String', 'DASHX_TARGET_ENVIRONMENT', localProperties.getProperty('DASHX_TARGET_ENVIRONMENT')
This seems like too much code. Maybe need to research some best practices around this @kiranattilicho

2022-08-05 06:29 UTC, merged